use anyhow::Result;
use std::collections::HashMap;

/// Event types that can be generated by windows
#[derive(Debug, Clone)]
pub enum WindowEvent {
    /// A printable or named key press event.
    KeyPress(String),
    /// The window requested closure.
    WindowClose,
    /// The window was resized to the given width and height.
    WindowResize(usize, usize),
}

/// Manages events for all graphics windows
pub struct EventManager {
    window_events: HashMap<String, Vec<WindowEvent>>,
}

impl EventManager {
    /// Create an empty event manager.
    pub fn new() -> Self {
        Self {
            window_events: HashMap::new(),
        }
    }

    /// Poll events for a specific window
    pub fn poll_window(&mut self, window_id: &str) -> Result<()> {
        // For now, just ensure the window has an event queue
        if !self.window_events.contains_key(window_id) {
            self.window_events.insert(window_id.to_string(), Vec::new());
        }
        Ok(())
    }

    /// Add an event to a window's queue
    pub fn push_event(&mut self, window_id: &str, event: WindowEvent) {
        let events = self
            .window_events
            .entry(window_id.to_string())
            .or_insert_with(Vec::new);
        events.push(event);
    }

    /// Get the next event for a window
    pub fn pop_event(&mut self, window_id: &str) -> Option<WindowEvent> {
        self.window_events.get_mut(window_id)?.pop()
    }

    /// Clear all events for a window
    pub fn clear_window_events(&mut self, window_id: &str) {
        if let Some(events) = self.window_events.get_mut(window_id) {
            events.clear();
        }
    }

    /// Clean up all event queues
    pub fn cleanup(&mut self) {
        self.window_events.clear();
    }
}
